export type AgentCategory = "coding" | "work";

export type AgentProfile = {
  id: string;
  name: string;
  maker: string;
  mark: string;
  color: string;
  category: AgentCategory;
  categoryLabel: string;
  role: string;
  oneLiner: string;
  bestFor: string;
  environment: string;
  tools: string;
  permission: string;
  autonomy: string;
  persistence: string;
  deployment: string;
  strengths: string[];
  limits: string[];
  goals: Array<"code" | "office" | "launch">;
  officialUrl: string;
  sourceLabel: string;
};

export const VERIFIED_AT = "2026-07-17";

export const agents: AgentProfile[] = [
  {
    id: "claude-code",
    name: "Claude Code",
    maker: "Anthropic",
    mark: "CC",
    color: "#d97745",
    category: "coding",
    categoryLabel: "编程 Agent",
    role: "终端软件工程 Agent",
    oneLiner: "在你的终端里理解代码库、修改文件并运行开发命令。",
    bestFor: "复杂代码理解、重构、调试，以及偏终端的开发工作流。",
    environment: "本机终端；可连接 IDE、脚本和 CI 工作流。",
    tools: "文件读写、Shell、代码搜索、Git、Web/MCP 扩展。",
    permission: "通过允许/禁止工具和 permission mode 控制；跳过权限提示属于高风险选项。",
    autonomy: "交互式协作，也可用 print mode 做有限轮数的非交互任务。",
    persistence: "支持继续或恢复会话；长期业务记忆不是核心产品边界。",
    deployment: "本机执行，AI 处理需要联网；可通过 Anthropic、Bedrock 或 Vertex AI 使用。",
    strengths: ["终端工作流直接", "代码库推理和多文件修改", "工具权限配置明确"],
    limits: ["主要服务软件开发", "效果依赖终端环境和上下文质量", "放宽命令权限后风险明显上升"],
    goals: ["code", "launch"],
    officialUrl: "https://docs.anthropic.com/en/docs/claude-code/cli-usage",
    sourceLabel: "Claude Code CLI 官方文档",
  },
  {
    id: "codex",
    name: "Codex",
    maker: "OpenAI",
    mark: "CX",
    color: "#111111",
    category: "coding",
    categoryLabel: "编程 Agent",
    role: "多端软件工程 Agent",
    oneLiner: "围绕代码仓库完成理解、修改、测试、审查和交付。",
    bestFor: "需要本地开发、Git 审查、并行工作树或云端任务协作的团队。",
    environment: "桌面应用、CLI、IDE、Web 与 OpenAI 管理的云端环境。",
    tools: "文件、Shell、Git、Web、MCP、技能、连接器和自动化。",
    permission: "默认提供只读/工作区写入沙箱、目录规则和按需审批。",
    autonomy: "可交互协作，也可在本地或云端独立执行、并行处理和定时运行。",
    persistence: "任务、会话、工作树和上下文可持续；长会话会压缩旧上下文。",
    deployment: "本机或 OpenAI 云端；产品体验主要围绕 OpenAI 模型与账户体系。",
    strengths: ["开发闭环完整", "Git、审查和工作树原生", "沙箱与审批边界细"],
    limits: ["核心仍是软件开发", "平台和模型选择相对集中", "云端与本地能力存在差异"],
    goals: ["code", "launch"],
    officialUrl: "https://learn.chatgpt.com/docs/glossary",
    sourceLabel: "Codex 官方术语与产品文档",
  },
  {
    id: "cursor",
    name: "Cursor",
    maker: "Anysphere",
    mark: "CU",
    color: "#646b73",
    category: "coding",
    categoryLabel: "编程 Agent",
    role: "AI 代码编辑器与后台 Agent",
    oneLiner: "把代码问答、编辑、终端和后台 Agent 放进同一个编辑器。",
    bestFor: "希望在熟悉的编辑器界面中高频协作、审阅 Diff 和启动后台任务的人。",
    environment: "本地 Cursor IDE、CLI，以及连接 GitHub 的 Web/移动后台 Agent。",
    tools: "代码库搜索、文件编辑、终端、Diff、GitHub 后台任务。",
    permission: "前台可审阅改动和批准命令；后台 Agent 在隔离环境中执行仓库任务。",
    autonomy: "Agent 模式可独立完成多步编码；Background Agent 可远程异步运行。",
    persistence: "支持会话恢复、后台任务和从 Web/移动端回到桌面继续。",
    deployment: "本地编辑器 + Cursor 托管的后台执行环境。",
    strengths: ["编辑器内反馈快", "代码上下文和 Diff 审阅顺手", "前台与后台任务衔接"],
    limits: ["围绕 Cursor 工作台", "后台任务需要仓库连接", "不是通用办公 Agent"],
    goals: ["code", "launch"],
    officialUrl: "https://docs.cursor.com/chat/overview",
    sourceLabel: "Cursor Agent 官方文档",
  },
  {
    id: "manus",
    name: "Manus",
    maker: "Manus",
    mark: "M",
    color: "#111111",
    category: "work",
    categoryLabel: "通用执行 Agent",
    role: "云端通用执行与桌面 Agent",
    oneLiner: "在独立云端电脑中规划并交付网站、报告、幻灯片等完整成果。",
    bestFor: "不想管理开发环境、希望直接委派研究和内容交付的用户。",
    environment: "云端沙箱、浏览器，以及授权后可操作本机文件和命令的桌面端。",
    tools: "浏览器、文件、终端、软件安装、连接器与本机命令行。",
    permission: "本机功能按文件夹授权，敏感命令会确认；浏览器会话需单独授权。",
    autonomy: "可自主规划长任务、创建子任务并在后台交付成果。",
    persistence: "云端文件系统、项目和任务线程可持续；支持多阶段交付。",
    deployment: "以托管云端为主，桌面端把执行边界延伸到用户电脑。",
    strengths: ["从任务到成品的闭环", "无需搭建本地开发环境", "研究、内容和建站覆盖广"],
    limits: ["复杂任务消耗 credits", "广泛工具权限需要复核", "精细工程控制不如专业 IDE"],
    goals: ["office", "launch"],
    officialUrl: "https://manus.im/docs/introduction/welcome",
    sourceLabel: "Manus 官方文档",
  },
  {
    id: "coze",
    name: "扣子 Coze",
    maker: "字节跳动",
    mark: "扣",
    color: "#6254f4",
    category: "work",
    categoryLabel: "职场与开发平台",
    role: "职场 Agent 与 Agent 开发平台",
    oneLiner: "既提供开箱即用的办公创作 Agent，也提供智能体、工作流和应用开发能力。",
    bestFor: "内容运营、办公产物、低代码工作流，以及快速发布 AI 应用。",
    environment: "托管 Web/移动产品、云端运行环境；另有开源开发与调试工具。",
    tools: "文档、PPT、表格、图片/音视频、技能、工作流、云电脑与云手机。",
    permission: "公开产品页未完整说明所有操作的细粒度确认模型，关键外部操作应人工核验。",
    autonomy: "支持长期任务、离线执行、技能调用和 7×24 云端运行。",
    persistence: "强调长期记忆、个性化资讯和持续任务。",
    deployment: "扣子托管平台；开发产品支持默认域名、自定义域名及部分私有化路径。",
    strengths: ["中文办公与内容形态丰富", "Agent、工作流和发布一体", "非开发者上手门槛低"],
    limits: ["产品线多，边界需要先选清", "细粒度权限公开信息有限", "深度本机工程控制不是核心"],
    goals: ["office", "launch"],
    officialUrl: "https://www.coze.cn/overview",
    sourceLabel: "扣子官方产品页",
  },
  {
    id: "workbuddy",
    name: "WorkBuddy",
    maker: "腾讯",
    mark: "WB",
    color: "#3778ff",
    category: "work",
    categoryLabel: "桌面办公 Agent",
    role: "全场景职场 AI 智能体",
    oneLiner: "面向 HR、运营、销售等岗位，跨文件和工具协同完成办公任务。",
    bestFor: "腾讯生态用户、团队办公、经营分析和重复跨工具流程。",
    environment: "Windows/macOS 桌面工作台，并与腾讯云及 QQ/企微生态衔接。",
    tools: "本地电脑操作、文档与表格、浏览器、多模型、团队和企业知识。",
    permission: "支持受控的本机执行；公开资料暂未完整披露统一的细粒度确认矩阵。",
    autonomy: "可拆解并执行多步骤办公任务，企业版还覆盖托管 Agent。",
    persistence: "桌面工作台承载日常任务和团队上下文；企业版支持资产沉淀。",
    deployment: "桌面客户端 + 腾讯云服务；企业版提供统一账户与权限管理。",
    strengths: ["中文职场场景明确", "腾讯办公生态连接", "个人到企业路径完整"],
    limits: ["开发能力不如专业 Coding Agent", "生态外连接需逐项确认", "新产品信息变化较快"],
    goals: ["office"],
    officialUrl: "https://www.codebuddy.cn/docs/workbuddy/From-Beginner-to-Expert-Guide/Product-Guide",
    sourceLabel: "腾讯 WorkBuddy 官方文档",
  },
  {
    id: "qoder",
    name: "Qoder",
    maker: "Qoder",
    mark: ">_",
    color: "#202522",
    category: "coding",
    categoryLabel: "编程 Agent",
    role: "Agentic Coding 平台",
    oneLiner: "用 Editor 做实时协作，用 Quest 把长期、多步骤开发任务交给 Agent。",
    bestFor: "希望在编辑器内编码，同时把较长任务委派给独立工作区的开发者。",
    environment: "Qoder Editor、Quest 独立窗口、CLI 与 JetBrains 插件。",
    tools: "代码编辑、Shell、项目搜索、MCP、知识引擎和任务看板。",
    permission: "Agent 执行文件和命令时由界面提示确认；具体行为依模式和设置变化。",
    autonomy: "Ask 用于问答，Agent 用于多文件实现，Quest 用于长期自主委派。",
    persistence: "知识引擎积累项目知识，Quest 保留任务状态和交付物。",
    deployment: "本机编辑器/CLI 为主，部分长期任务由平台工作区承载。",
    strengths: ["协作与委派模式分明", "长期任务看板可观察", "项目知识积累"],
    limits: ["主要面向软件开发", "不同工作区学习成本较高", "生态成熟度仍在快速变化"],
    goals: ["code", "launch"],
    officialUrl: "https://docs.qoder.com/",
    sourceLabel: "Qoder 官方文档",
  },
  {
    id: "dumate",
    name: "DuMate",
    maker: "百度",
    mark: "D",
    color: "#42bfc9",
    category: "work",
    categoryLabel: "本地办公 Agent",
    role: "本地跨应用办公 Agent",
    oneLiner: "围绕本地文件、数据分析和重复操作，把自然语言变成可执行流程。",
    bestFor: "文件整理、批量格式转换、表格分析和桌面自动化。",
    environment: "Windows/macOS 桌面客户端，并提供移动 App。",
    tools: "本地文件、Office/PDF、数据处理、跨应用操作、录制回放、Skills。",
    permission: "官方强调文件夹级权限控制和风险操作二次确认。",
    autonomy: "可规划复杂任务、执行定时调度并把操作沉淀为技能。",
    persistence: "支持技能、知识库、成果和标准流程沉淀。",
    deployment: "本地客户端为核心；个人版与企业版分别提供服务能力。",
    strengths: ["本地办公自动化直接", "权限边界表达清楚", "中文文件处理场景丰富"],
    limits: ["软件工程不是重点", "高级模型与沙箱细节公开较少", "跨应用成功率依赖桌面环境"],
    goals: ["office"],
    officialUrl: "https://www.dumate.cn/",
    sourceLabel: "DuMate 官方产品页",
  },
  {
    id: "kimi-work",
    name: "Kimi Work",
    maker: "月之暗面",
    mark: "K",
    color: "#111111",
    category: "work",
    categoryLabel: "本地知识工作 Agent",
    role: "桌面本地知识工作 Agent",
    oneLiner: "挂载本地文件夹、操作浏览器、运行代码，并用 Agent Swarm 处理长任务。",
    bestFor: "研究、金融数据、长文档、报告生成和需要定时执行的知识工作。",
    environment: "Windows 与 Apple silicon macOS 桌面端。",
    tools: "本地文件、WebBridge 浏览器、Python/Shell、定时任务和金融数据源。",
    permission: "修改、覆盖本地文件或运行代码前，官方说明会明确请求授权。",
    autonomy: "支持 Agent Swarm、后台代码执行和 24/7 Cron 自动化。",
    persistence: "本地工作区、定时任务和长期运行流程可持续。",
    deployment: "桌面本地 Agent；要让夜间任务持续需保持电脑唤醒。",
    strengths: ["本地文件与浏览器结合", "长任务和并行 Agent", "知识工作与研究定位清晰"],
    limits: ["持续任务依赖电脑在线", "广泛本地权限需谨慎", "专业代码审查不如 Coding Agent"],
    goals: ["office", "launch"],
    officialUrl: "https://www.kimi.com/products/kimi-work",
    sourceLabel: "Kimi Work 官方产品页",
  },
  {
    id: "trae",
    name: "Trae",
    maker: "字节跳动",
    mark: "T",
    color: "#e84b35",
    category: "coding",
    categoryLabel: "编程 Agent",
    role: "AI IDE 与 SOLO Coding Agent",
    oneLiner: "在 IDE 中协作编码，或让 SOLO Agent 主导从目标到完整项目的开发。",
    bestFor: "Vibe Coding、0→1 原型，以及希望在 IDE 与高自主模式间切换的人。",
    environment: "TRAE IDE、插件，以及不同地区提供的 SOLO/Work 云端或桌面形态。",
    tools: "编辑器、终端、文档、网页、预览浏览器、MCP、自定义 Agent。",
    permission: "可配置自动接受变更、自动运行和命令黑名单；高自主模式需加强人工审阅。",
    autonomy: "IDE 模式协作，SOLO 模式可自主规划、调用工具并推进完整开发流程。",
    persistence: "项目规则、上下文、自定义 Agent 和任务状态可复用。",
    deployment: "本地 IDE 为主；SOLO 与企业能力因地区、版本和套餐有所差异。",
    strengths: ["0→1 产品流程突出", "IDE 与自主模式切换", "MCP 和自定义 Agent 丰富"],
    limits: ["版本与地区差异明显", "自动接受变更需要严格复核", "非技术办公不是核心"],
    goals: ["code", "launch"],
    officialUrl: "https://www.trae.ai/",
    sourceLabel: "TRAE 官方产品页",
  },
];

export const comparisonFields: Array<{
  key: keyof AgentProfile;
  label: string;
  hint: string;
}> = [
  { key: "role", label: "产品角色", hint: "先确认它到底是哪一类 Agent" },
  { key: "bestFor", label: "核心任务", hint: "最适合交付什么结果" },
  { key: "environment", label: "运行环境", hint: "任务实际在哪里发生" },
  { key: "tools", label: "工具边界", hint: "它能读取与调用什么" },
  { key: "permission", label: "权限边界", hint: "哪些动作需要确认" },
  { key: "autonomy", label: "自主程度", hint: "你要盯多紧" },
  { key: "persistence", label: "持续性", hint: "会话、记忆和定时能力" },
  { key: "deployment", label: "数据与部署", hint: "本地、云端还是混合" },
];
